apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - port: 8082
      targetPort: 8082
      name: port1
    - port: 9092
      targetPort: 9092
      name: port2