java_binary(
    name = 'TutReact',
    srcs = glob(['src/main/java/com/greglturnquist/payroll/*.java']),
    main_class = 'com.greglturnquist.payroll.ReactAndSpringDataRestApplication',

    deps = [

            '@maven//:org_springframework_boot_spring_boot',

            '@maven//:org_springframework_boot_spring_boot_autoconfigure',

            '@maven//:org_springframework_boot_spring_boot_starter_web',

            '@maven//:org_springframework_boot_spring_boot_starter_data_jpa',

            '@maven//:org_springframework_boot_spring_boot_starter_tomcat',

            '@maven//:org_springframework_boot_spring_boot_starter_thymeleaf',

            '@maven//:com_h2database_h2',

            '@maven//:org_springframework_spring_web',

            '@maven//:org_webjars_Rest',

        ],

        resources = glob(["src/main/resources/**"]),
  )

