apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
        version: v0.1
    spec:
      containers:
        - name: webserver
          image: pmonteiro1211790/devops-21-22-lmn-1211790:ca4_part_2_webv2
          ports:
            - containerPort: 8080